### ISSUE TITLE
Is the user agent list updated regularly?

### ISSUE THREAD

**Issue by jacob-betmatic** [jnrbsn/python-latest-user-agents#1]
From the codebase, I can see it's downloading the user agent list from https://jnrbsn.github.io/user-agents/user-agents.json.
I wonder if this link is updated with new user agents regularly.

**Comment by wilrib** [comment]
Yes
Look the file "user-agents.json" on https://github.com/jnrbsn/user-agents, is updated daily.

**Comment by Ed1123** [comment]
It seems so, but it keeps some outdated ones. Like for today:
- Mozilla/5.0 (Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
- Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
- Mozilla/5.0 (X11; Linux i686; rv:102.0) Gecko/20100101 Firefox/102.0
- Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:102.0) Gecko/20100101 Firefox/102.0
- Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
